version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/rails-docker-heroku
    steps:
      - checkout:
          path: ~/rails-docker-heroku
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/postgres
        environment:
          POSTGRES_ROOT_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      POSTGRES_HOST: 127.0.0.1
      RAILS_ENV: test
    working_directory: ~/rails-docker-heroku
    steps:
      - checkout:
          path: ~/rails-docker-heroku
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
