version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    working_directory: ~/rails-docker-heroku
    steps:
      - checkout:
          path: ~/rails-docker-heroku
      - ruby/install-deps
  test:
    docker:
      - image: cimg/ruby:2.7-node
      - image: cimg/postgres:14.0
        environment: # add POSTGRES environment variables.
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    # Ruby/Rails 固有の環境変数をプライマリコンテナに適用します。
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: password
      RAILS_ENV: test
    steps:
      - checkout:
          path: ~/rails-docker-heroku
      - ruby/install-deps
      # - run:
      #     name: Database setup
      #     command: bundle exec rails db:migrate
      # - run:
      #     name: test
      #     command: bundle exec rspec

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
